version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: aegis-crypt-postgres
    environment:
      POSTGRES_DB: aegis_crypt
      POSTGRES_USER: aegis
      POSTGRES_PASSWORD: aegis
    ports:
      - "5432:5432"
    volumes:
      - aegis_crypt_pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: aegis-crypt-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  aegis_crypt_pgdata: